services:
  - type: web
    name: grow-a-garden-stock-tracker
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
